/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const ClassId = IDL.Nat;
export const Class = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'studentIds' : IDL.Vec(UserId),
  'classId' : ClassId,
  'teacherId' : UserId,
});
export const QuestionType = IDL.Variant({
  'shortAnswer' : IDL.Null,
  'essay' : IDL.Null,
  'multipleChoice' : IDL.Null,
});
export const QuestionId = IDL.Nat;
export const Question = IDL.Record({
  'pointValue' : IDL.Nat,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Opt(IDL.Text),
  'questionType' : QuestionType,
  'questionId' : QuestionId,
  'options' : IDL.Vec(IDL.Text),
});
export const ExamStatus = IDL.Variant({
  'closed' : IDL.Null,
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ExamId = IDL.Nat;
export const Exam = IDL.Record({
  'status' : ExamStatus,
  'title' : IDL.Text,
  'answerKeyRef' : IDL.Opt(ExternalBlob),
  'createdAt' : Timestamp,
  'rubricRef' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'classId' : ClassId,
  'durationMinutes' : IDL.Opt(IDL.Nat),
  'teacherId' : UserId,
  'questions' : IDL.Vec(Question),
  'examId' : ExamId,
  'scheduledAt' : IDL.Opt(Timestamp),
});
export const LogId = IDL.Nat;
export const ActivityLog = IDL.Record({
  'action' : IDL.Text,
  'actorName' : IDL.Text,
  'actorId' : UserId,
  'logId' : LogId,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const ClassAnalytics = IDL.Record({
  'topStudents' : IDL.Vec(IDL.Tuple(UserId, IDL.Float64)),
  'examCount' : IDL.Nat,
  'failingStudents' : IDL.Vec(IDL.Tuple(UserId, IDL.Float64)),
  'submissionCount' : IDL.Nat,
  'averageScore' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'pendingSubmissions' : IDL.Nat,
  'recentActivityCount' : IDL.Nat,
  'totalStudents' : IDL.Nat,
  'totalAdmins' : IDL.Nat,
  'totalTeachers' : IDL.Nat,
  'activeExams' : IDL.Nat,
});
export const SubmissionStatus = IDL.Variant({
  'graded' : IDL.Null,
  'submitted' : IDL.Null,
  'grading' : IDL.Null,
});
export const AnswerEntry = IDL.Record({
  'text' : IDL.Text,
  'questionId' : QuestionId,
});
export const QuestionFeedback = IDL.Record({
  'feedback' : IDL.Text,
  'score' : IDL.Float64,
  'questionId' : QuestionId,
});
export const SubmissionId = IDL.Nat;
export const Submission = IDL.Record({
  'status' : SubmissionStatus,
  'studentId' : UserId,
  'textAnswers' : IDL.Vec(AnswerEntry),
  'submittedAt' : Timestamp,
  'aiFeedback' : IDL.Vec(QuestionFeedback),
  'submissionId' : SubmissionId,
  'examId' : ExamId,
  'aiScore' : IDL.Opt(IDL.Float64),
  'fileRef' : IDL.Opt(ExternalBlob),
});
export const PerformanceRecord = IDL.Record({
  'examTitle' : IDL.Text,
  'submittedAt' : Timestamp,
  'finalScore' : IDL.Opt(IDL.Float64),
  'examId' : ExamId,
});
export const ResultId = IDL.Nat;
export const Result = IDL.Record({
  'teacherRemarks' : IDL.Text,
  'overriddenBy' : IDL.Opt(UserId),
  'gradedAt' : Timestamp,
  'resultId' : ResultId,
  'finalScore' : IDL.Float64,
  'submissionId' : SubmissionId,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createClass' : IDL.Func([IDL.Text], [Class], []),
  'createExam' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ClassId,
        IDL.Vec(Question),
        IDL.Opt(Timestamp),
        IDL.Opt(IDL.Nat),
      ],
      [Exam],
      [],
    ),
  'getActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getAssignedExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClassAnalytics' : IDL.Func([ClassId], [ClassAnalytics], ['query']),
  'getClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getExamDetail' : IDL.Func([ExamId], [IDL.Opt(Exam)], ['query']),
  'getExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getPerformanceHistory' : IDL.Func(
      [],
      [IDL.Vec(PerformanceRecord)],
      ['query'],
    ),
  'getSubmissionResult' : IDL.Func(
      [SubmissionId],
      [IDL.Opt(Result)],
      ['query'],
    ),
  'getSubmissions' : IDL.Func([ExamId], [IDL.Vec(Submission)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserId, UserProfile))],
      ['query'],
    ),
  'inviteUser' : IDL.Func([UserId, IDL.Text, IDL.Text, UserRole], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'overrideScore' : IDL.Func([SubmissionId, IDL.Float64, IDL.Text], [], []),
  'publishExam' : IDL.Func([ExamId], [], []),
  'resetUserPassword' : IDL.Func([UserId], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
  'submitExam' : IDL.Func(
      [ExamId, IDL.Vec(AnswerEntry), IDL.Opt(ExternalBlob)],
      [Submission],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerAIGrading' : IDL.Func([SubmissionId], [], []),
  'updateClass' : IDL.Func([ClassId, IDL.Text], [], []),
  'updateExam' : IDL.Func(
      [
        ExamId,
        IDL.Text,
        IDL.Text,
        IDL.Vec(Question),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(Timestamp),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateUserRole' : IDL.Func([UserId, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const ClassId = IDL.Nat;
  const Class = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'studentIds' : IDL.Vec(UserId),
    'classId' : ClassId,
    'teacherId' : UserId,
  });
  const QuestionType = IDL.Variant({
    'shortAnswer' : IDL.Null,
    'essay' : IDL.Null,
    'multipleChoice' : IDL.Null,
  });
  const QuestionId = IDL.Nat;
  const Question = IDL.Record({
    'pointValue' : IDL.Nat,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Opt(IDL.Text),
    'questionType' : QuestionType,
    'questionId' : QuestionId,
    'options' : IDL.Vec(IDL.Text),
  });
  const ExamStatus = IDL.Variant({
    'closed' : IDL.Null,
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ExamId = IDL.Nat;
  const Exam = IDL.Record({
    'status' : ExamStatus,
    'title' : IDL.Text,
    'answerKeyRef' : IDL.Opt(ExternalBlob),
    'createdAt' : Timestamp,
    'rubricRef' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'classId' : ClassId,
    'durationMinutes' : IDL.Opt(IDL.Nat),
    'teacherId' : UserId,
    'questions' : IDL.Vec(Question),
    'examId' : ExamId,
    'scheduledAt' : IDL.Opt(Timestamp),
  });
  const LogId = IDL.Nat;
  const ActivityLog = IDL.Record({
    'action' : IDL.Text,
    'actorName' : IDL.Text,
    'actorId' : UserId,
    'logId' : LogId,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const ClassAnalytics = IDL.Record({
    'topStudents' : IDL.Vec(IDL.Tuple(UserId, IDL.Float64)),
    'examCount' : IDL.Nat,
    'failingStudents' : IDL.Vec(IDL.Tuple(UserId, IDL.Float64)),
    'submissionCount' : IDL.Nat,
    'averageScore' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'pendingSubmissions' : IDL.Nat,
    'recentActivityCount' : IDL.Nat,
    'totalStudents' : IDL.Nat,
    'totalAdmins' : IDL.Nat,
    'totalTeachers' : IDL.Nat,
    'activeExams' : IDL.Nat,
  });
  const SubmissionStatus = IDL.Variant({
    'graded' : IDL.Null,
    'submitted' : IDL.Null,
    'grading' : IDL.Null,
  });
  const AnswerEntry = IDL.Record({
    'text' : IDL.Text,
    'questionId' : QuestionId,
  });
  const QuestionFeedback = IDL.Record({
    'feedback' : IDL.Text,
    'score' : IDL.Float64,
    'questionId' : QuestionId,
  });
  const SubmissionId = IDL.Nat;
  const Submission = IDL.Record({
    'status' : SubmissionStatus,
    'studentId' : UserId,
    'textAnswers' : IDL.Vec(AnswerEntry),
    'submittedAt' : Timestamp,
    'aiFeedback' : IDL.Vec(QuestionFeedback),
    'submissionId' : SubmissionId,
    'examId' : ExamId,
    'aiScore' : IDL.Opt(IDL.Float64),
    'fileRef' : IDL.Opt(ExternalBlob),
  });
  const PerformanceRecord = IDL.Record({
    'examTitle' : IDL.Text,
    'submittedAt' : Timestamp,
    'finalScore' : IDL.Opt(IDL.Float64),
    'examId' : ExamId,
  });
  const ResultId = IDL.Nat;
  const Result = IDL.Record({
    'teacherRemarks' : IDL.Text,
    'overriddenBy' : IDL.Opt(UserId),
    'gradedAt' : Timestamp,
    'resultId' : ResultId,
    'finalScore' : IDL.Float64,
    'submissionId' : SubmissionId,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createClass' : IDL.Func([IDL.Text], [Class], []),
    'createExam' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ClassId,
          IDL.Vec(Question),
          IDL.Opt(Timestamp),
          IDL.Opt(IDL.Nat),
        ],
        [Exam],
        [],
      ),
    'getActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getAssignedExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClassAnalytics' : IDL.Func([ClassId], [ClassAnalytics], ['query']),
    'getClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getExamDetail' : IDL.Func([ExamId], [IDL.Opt(Exam)], ['query']),
    'getExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getPerformanceHistory' : IDL.Func(
        [],
        [IDL.Vec(PerformanceRecord)],
        ['query'],
      ),
    'getSubmissionResult' : IDL.Func(
        [SubmissionId],
        [IDL.Opt(Result)],
        ['query'],
      ),
    'getSubmissions' : IDL.Func([ExamId], [IDL.Vec(Submission)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserId, UserProfile))],
        ['query'],
      ),
    'inviteUser' : IDL.Func([UserId, IDL.Text, IDL.Text, UserRole], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'overrideScore' : IDL.Func([SubmissionId, IDL.Float64, IDL.Text], [], []),
    'publishExam' : IDL.Func([ExamId], [], []),
    'resetUserPassword' : IDL.Func([UserId], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
    'submitExam' : IDL.Func(
        [ExamId, IDL.Vec(AnswerEntry), IDL.Opt(ExternalBlob)],
        [Submission],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerAIGrading' : IDL.Func([SubmissionId], [], []),
    'updateClass' : IDL.Func([ClassId, IDL.Text], [], []),
    'updateExam' : IDL.Func(
        [
          ExamId,
          IDL.Text,
          IDL.Text,
          IDL.Vec(Question),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(Timestamp),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateUserRole' : IDL.Func([UserId, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };