/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'action' : string,
  'actorName' : string,
  'actorId' : UserId,
  'logId' : LogId,
  'timestamp' : Timestamp,
  'details' : string,
}
export interface AnswerEntry { 'text' : string, 'questionId' : QuestionId }
export interface Class {
  'name' : string,
  'createdAt' : Timestamp,
  'studentIds' : Array<UserId>,
  'classId' : ClassId,
  'teacherId' : UserId,
}
export interface ClassAnalytics {
  'topStudents' : Array<[UserId, number]>,
  'examCount' : bigint,
  'failingStudents' : Array<[UserId, number]>,
  'submissionCount' : bigint,
  'averageScore' : number,
}
export type ClassId = bigint;
export interface DashboardStats {
  'pendingSubmissions' : bigint,
  'recentActivityCount' : bigint,
  'totalStudents' : bigint,
  'totalAdmins' : bigint,
  'totalTeachers' : bigint,
  'activeExams' : bigint,
}
export interface Exam {
  'status' : ExamStatus,
  'title' : string,
  'answerKeyRef' : [] | [ExternalBlob],
  'createdAt' : Timestamp,
  'rubricRef' : [] | [ExternalBlob],
  'description' : string,
  'classId' : ClassId,
  'durationMinutes' : [] | [bigint],
  'teacherId' : UserId,
  'questions' : Array<Question>,
  'examId' : ExamId,
  'scheduledAt' : [] | [Timestamp],
}
export type ExamId = bigint;
export type ExamStatus = { 'closed' : null } |
  { 'published' : null } |
  { 'draft' : null };
export type ExternalBlob = Uint8Array;
export type LogId = bigint;
export interface PerformanceRecord {
  'examTitle' : string,
  'submittedAt' : Timestamp,
  'finalScore' : [] | [number],
  'examId' : ExamId,
}
export interface Question {
  'pointValue' : bigint,
  'text' : string,
  'correctAnswer' : [] | [string],
  'questionType' : QuestionType,
  'questionId' : QuestionId,
  'options' : Array<string>,
}
export interface QuestionFeedback {
  'feedback' : string,
  'score' : number,
  'questionId' : QuestionId,
}
export type QuestionId = bigint;
export type QuestionType = { 'shortAnswer' : null } |
  { 'essay' : null } |
  { 'multipleChoice' : null };
export interface Result {
  'teacherRemarks' : string,
  'overriddenBy' : [] | [UserId],
  'gradedAt' : Timestamp,
  'resultId' : ResultId,
  'finalScore' : number,
  'submissionId' : SubmissionId,
}
export type ResultId = bigint;
export interface Submission {
  'status' : SubmissionStatus,
  'studentId' : UserId,
  'textAnswers' : Array<AnswerEntry>,
  'submittedAt' : Timestamp,
  'aiFeedback' : Array<QuestionFeedback>,
  'submissionId' : SubmissionId,
  'examId' : ExamId,
  'aiScore' : [] | [number],
  'fileRef' : [] | [ExternalBlob],
}
export type SubmissionId = bigint;
export type SubmissionStatus = { 'graded' : null } |
  { 'submitted' : null } |
  { 'grading' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'teacher' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createClass' : ActorMethod<[string], Class>,
  'createExam' : ActorMethod<
    [string, string, ClassId, Array<Question>, [] | [Timestamp], [] | [bigint]],
    Exam
  >,
  'getActivityLogs' : ActorMethod<[], Array<ActivityLog>>,
  'getAssignedExams' : ActorMethod<[], Array<Exam>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClassAnalytics' : ActorMethod<[ClassId], ClassAnalytics>,
  'getClasses' : ActorMethod<[], Array<Class>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getExamDetail' : ActorMethod<[ExamId], [] | [Exam]>,
  'getExams' : ActorMethod<[], Array<Exam>>,
  'getMySubmissions' : ActorMethod<[], Array<Submission>>,
  'getPerformanceHistory' : ActorMethod<[], Array<PerformanceRecord>>,
  'getSubmissionResult' : ActorMethod<[SubmissionId], [] | [Result]>,
  'getSubmissions' : ActorMethod<[ExamId], Array<Submission>>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<[UserId, UserProfile]>>,
  'inviteUser' : ActorMethod<[UserId, string, string, UserRole], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'overrideScore' : ActorMethod<[SubmissionId, number, string], undefined>,
  'publishExam' : ActorMethod<[ExamId], undefined>,
  'resetUserPassword' : ActorMethod<[UserId], string>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'setOpenAIKey' : ActorMethod<[string], undefined>,
  'submitExam' : ActorMethod<
    [ExamId, Array<AnswerEntry>, [] | [ExternalBlob]],
    Submission
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerAIGrading' : ActorMethod<[SubmissionId], undefined>,
  'updateClass' : ActorMethod<[ClassId, string], undefined>,
  'updateExam' : ActorMethod<
    [
      ExamId,
      string,
      string,
      Array<Question>,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [Timestamp],
      [] | [bigint],
    ],
    undefined
  >,
  'updateUserRole' : ActorMethod<[UserId, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];