/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Class {
    name: string;
    createdAt: Timestamp;
    studentIds: Array<UserId>;
    classId: ClassId;
    teacherId: UserId;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type ResultId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type SubmissionId = bigint;
export interface PerformanceRecord {
    examTitle: string;
    submittedAt: Timestamp;
    finalScore?: number;
    examId: ExamId;
}
export type ExamId = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Exam {
    status: ExamStatus;
    title: string;
    answerKeyRef?: ExternalBlob;
    createdAt: Timestamp;
    rubricRef?: ExternalBlob;
    description: string;
    classId: ClassId;
    durationMinutes?: bigint;
    teacherId: UserId;
    questions: Array<Question>;
    examId: ExamId;
    scheduledAt?: Timestamp;
}
export type ClassId = bigint;
export interface Submission {
    status: SubmissionStatus;
    studentId: UserId;
    textAnswers: Array<AnswerEntry>;
    submittedAt: Timestamp;
    aiFeedback: Array<QuestionFeedback>;
    submissionId: SubmissionId;
    examId: ExamId;
    aiScore?: number;
    fileRef?: ExternalBlob;
}
export interface QuestionFeedback {
    feedback: string;
    score: number;
    questionId: QuestionId;
}
export interface ActivityLog {
    action: string;
    actorName: string;
    actorId: UserId;
    logId: LogId;
    timestamp: Timestamp;
    details: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type QuestionId = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ClassAnalytics {
    topStudents: Array<[UserId, number]>;
    examCount: bigint;
    failingStudents: Array<[UserId, number]>;
    submissionCount: bigint;
    averageScore: number;
}
export interface DashboardStats {
    pendingSubmissions: bigint;
    recentActivityCount: bigint;
    totalStudents: bigint;
    totalAdmins: bigint;
    totalTeachers: bigint;
    activeExams: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type LogId = bigint;
export type UserId = Principal;
export interface Result {
    teacherRemarks: string;
    overriddenBy?: UserId;
    gradedAt: Timestamp;
    resultId: ResultId;
    finalScore: number;
    submissionId: SubmissionId;
}
export interface Question {
    pointValue: bigint;
    text: string;
    correctAnswer?: string;
    questionType: QuestionType;
    questionId: QuestionId;
    options: Array<string>;
}
export interface UserProfile {
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
}
export interface AnswerEntry {
    text: string;
    questionId: QuestionId;
}
export enum ExamStatus {
    closed = "closed",
    published = "published",
    draft = "draft"
}
export enum QuestionType {
    shortAnswer = "shortAnswer",
    essay = "essay",
    multipleChoice = "multipleChoice"
}
export enum SubmissionStatus {
    graded = "graded",
    submitted = "submitted",
    grading = "grading"
}
export enum UserRole {
    admin = "admin",
    teacher = "teacher",
    student = "student"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createClass(name: string): Promise<Class>;
    createExam(title: string, description: string, classId: ClassId, questions: Array<Question>, scheduledAt: Timestamp | null, durationMinutes: bigint | null): Promise<Exam>;
    getActivityLogs(): Promise<Array<ActivityLog>>;
    getAssignedExams(): Promise<Array<Exam>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getClassAnalytics(classId: ClassId): Promise<ClassAnalytics>;
    getClasses(): Promise<Array<Class>>;
    getDashboardStats(): Promise<DashboardStats>;
    getExamDetail(examId: ExamId): Promise<Exam | null>;
    getExams(): Promise<Array<Exam>>;
    getMySubmissions(): Promise<Array<Submission>>;
    getPerformanceHistory(): Promise<Array<PerformanceRecord>>;
    getSubmissionResult(submissionId: SubmissionId): Promise<Result | null>;
    getSubmissions(examId: ExamId): Promise<Array<Submission>>;
    getUserProfile(user: UserId): Promise<UserProfile | null>;
    getUsers(): Promise<Array<[UserId, UserProfile]>>;
    inviteUser(targetPrincipal: UserId, name: string, email: string, role: UserRole): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    overrideScore(submissionId: SubmissionId, finalScore: number, teacherRemarks: string): Promise<void>;
    publishExam(examId: ExamId): Promise<void>;
    resetUserPassword(targetPrincipal: UserId): Promise<string>;
    saveCallerUserProfile(name: string, email: string): Promise<void>;
    setOpenAIKey(key: string): Promise<void>;
    submitExam(examId: ExamId, textAnswers: Array<AnswerEntry>, fileRef: ExternalBlob | null): Promise<Submission>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    triggerAIGrading(submissionId: SubmissionId): Promise<void>;
    updateClass(classId: ClassId, name: string): Promise<void>;
    updateExam(examId: ExamId, title: string, description: string, questions: Array<Question>, answerKeyRef: ExternalBlob | null, rubricRef: ExternalBlob | null, scheduledAt: Timestamp | null, durationMinutes: bigint | null): Promise<void>;
    updateUserRole(targetPrincipal: UserId, role: UserRole): Promise<void>;
}
import type { AnswerEntry as _AnswerEntry, ClassId as _ClassId, Exam as _Exam, ExamId as _ExamId, ExamStatus as _ExamStatus, ExternalBlob as _ExternalBlob, PerformanceRecord as _PerformanceRecord, Question as _Question, QuestionFeedback as _QuestionFeedback, QuestionId as _QuestionId, QuestionType as _QuestionType, Result as _Result, ResultId as _ResultId, Submission as _Submission, SubmissionId as _SubmissionId, SubmissionStatus as _SubmissionStatus, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClass(arg0: string): Promise<Class> {
        if (this.processError) {
            try {
                const result = await this.actor.createClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClass(arg0);
            return result;
        }
    }
    async createExam(arg0: string, arg1: string, arg2: ClassId, arg3: Array<Question>, arg4: Timestamp | null, arg5: bigint | null): Promise<Exam> {
        if (this.processError) {
            try {
                const result = await this.actor.createExam(arg0, arg1, arg2, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Exam_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExam(arg0, arg1, arg2, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Exam_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLogs(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogs();
            return result;
        }
    }
    async getAssignedExams(): Promise<Array<Exam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedExams();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedExams();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClassAnalytics(arg0: ClassId): Promise<ClassAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassAnalytics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassAnalytics(arg0);
            return result;
        }
    }
    async getClasses(): Promise<Array<Class>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClasses();
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getExamDetail(arg0: ExamId): Promise<Exam | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamDetail(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamDetail(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExams(): Promise<Array<Exam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExams();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExams();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmissions();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmissions();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerformanceHistory(): Promise<Array<PerformanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerformanceHistory();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerformanceHistory();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionResult(arg0: SubmissionId): Promise<Result | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionResult(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionResult(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissions(arg0: ExamId): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissions(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissions(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<[UserId, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async inviteUser(arg0: UserId, arg1: string, arg2: string, arg3: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteUser(arg0, arg1, arg2, to_candid_UserRole_n54(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteUser(arg0, arg1, arg2, to_candid_UserRole_n54(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async overrideScore(arg0: SubmissionId, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.overrideScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.overrideScore(arg0, arg1, arg2);
            return result;
        }
    }
    async publishExam(arg0: ExamId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishExam(arg0);
            return result;
        }
    }
    async resetUserPassword(arg0: UserId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserPassword(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return result;
        }
    }
    async setOpenAIKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAIKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAIKey(arg0);
            return result;
        }
    }
    async submitExam(arg0: ExamId, arg1: Array<AnswerEntry>, arg2: ExternalBlob | null): Promise<Submission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitExam(arg0, arg1, await to_candid_opt_n56(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Submission_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitExam(arg0, arg1, await to_candid_opt_n56(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Submission_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async triggerAIGrading(arg0: SubmissionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerAIGrading(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerAIGrading(arg0);
            return result;
        }
    }
    async updateClass(arg0: ClassId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClass(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClass(arg0, arg1);
            return result;
        }
    }
    async updateExam(arg0: ExamId, arg1: string, arg2: string, arg3: Array<Question>, arg4: ExternalBlob | null, arg5: ExternalBlob | null, arg6: Timestamp | null, arg7: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExam(arg0, arg1, arg2, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n56(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n56(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExam(arg0, arg1, arg2, to_candid_vec_n10(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n56(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n56(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateUserRole(arg0: UserId, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ExamStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExamStatus): ExamStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_Exam_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exam): Promise<Exam> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PerformanceRecord_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PerformanceRecord): PerformanceRecord {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_Submission_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Promise<Submission> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Exam]): Promise<Exam | null> {
    return value.length === 0 ? null : await from_candid_Exam_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Result]): Result | null {
    return value.length === 0 ? null : from_candid_Result_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ExamStatus;
    title: string;
    answerKeyRef: [] | [_ExternalBlob];
    createdAt: _Timestamp;
    rubricRef: [] | [_ExternalBlob];
    description: string;
    classId: _ClassId;
    durationMinutes: [] | [bigint];
    teacherId: _UserId;
    questions: Array<_Question>;
    examId: _ExamId;
    scheduledAt: [] | [_Timestamp];
}): Promise<{
    status: ExamStatus;
    title: string;
    answerKeyRef?: ExternalBlob;
    createdAt: Timestamp;
    rubricRef?: ExternalBlob;
    description: string;
    classId: ClassId;
    durationMinutes?: bigint;
    teacherId: UserId;
    questions: Array<Question>;
    examId: ExamId;
    scheduledAt?: Timestamp;
}> {
    return {
        status: from_candid_ExamStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        answerKeyRef: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.answerKeyRef)),
        createdAt: value.createdAt,
        rubricRef: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.rubricRef)),
        description: value.description,
        classId: value.classId,
        durationMinutes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.durationMinutes)),
        teacherId: value.teacherId,
        questions: from_candid_vec_n23(_uploadFile, _downloadFile, value.questions),
        examId: value.examId,
        scheduledAt: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.scheduledAt))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pointValue: bigint;
    text: string;
    correctAnswer: [] | [string];
    questionType: _QuestionType;
    questionId: _QuestionId;
    options: Array<string>;
}): {
    pointValue: bigint;
    text: string;
    correctAnswer?: string;
    questionType: QuestionType;
    questionId: QuestionId;
    options: Array<string>;
} {
    return {
        pointValue: value.pointValue,
        text: value.text,
        correctAnswer: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.correctAnswer)),
        questionType: from_candid_QuestionType_n27(_uploadFile, _downloadFile, value.questionType),
        questionId: value.questionId,
        options: value.options
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
}): {
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n34(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubmissionStatus;
    studentId: _UserId;
    textAnswers: Array<_AnswerEntry>;
    submittedAt: _Timestamp;
    aiFeedback: Array<_QuestionFeedback>;
    submissionId: _SubmissionId;
    examId: _ExamId;
    aiScore: [] | [number];
    fileRef: [] | [_ExternalBlob];
}): Promise<{
    status: SubmissionStatus;
    studentId: UserId;
    textAnswers: Array<AnswerEntry>;
    submittedAt: Timestamp;
    aiFeedback: Array<QuestionFeedback>;
    submissionId: SubmissionId;
    examId: ExamId;
    aiScore?: number;
    fileRef?: ExternalBlob;
}> {
    return {
        status: from_candid_SubmissionStatus_n42(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        textAnswers: value.textAnswers,
        submittedAt: value.submittedAt,
        aiFeedback: value.aiFeedback,
        submissionId: value.submissionId,
        examId: value.examId,
        aiScore: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.aiScore)),
        fileRef: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.fileRef))
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    examTitle: string;
    submittedAt: _Timestamp;
    finalScore: [] | [number];
    examId: _ExamId;
}): {
    examTitle: string;
    submittedAt: Timestamp;
    finalScore?: number;
    examId: ExamId;
} {
    return {
        examTitle: value.examTitle,
        submittedAt: value.submittedAt,
        finalScore: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.finalScore)),
        examId: value.examId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teacherRemarks: string;
    overriddenBy: [] | [_UserId];
    gradedAt: _Timestamp;
    resultId: _ResultId;
    finalScore: number;
    submissionId: _SubmissionId;
}): {
    teacherRemarks: string;
    overriddenBy?: UserId;
    gradedAt: Timestamp;
    resultId: ResultId;
    finalScore: number;
    submissionId: SubmissionId;
} {
    return {
        teacherRemarks: value.teacherRemarks,
        overriddenBy: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.overriddenBy)),
        gradedAt: value.gradedAt,
        resultId: value.resultId,
        finalScore: value.finalScore,
        submissionId: value.submissionId
    };
}
function from_candid_tuple_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_UserId, _UserProfile]): [UserId, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    published: null;
} | {
    draft: null;
}): ExamStatus {
    return "closed" in value ? ExamStatus.closed : "published" in value ? ExamStatus.published : "draft" in value ? ExamStatus.draft : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shortAnswer: null;
} | {
    essay: null;
} | {
    multipleChoice: null;
}): QuestionType {
    return "shortAnswer" in value ? QuestionType.shortAnswer : "essay" in value ? QuestionType.essay : "multipleChoice" in value ? QuestionType.multipleChoice : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "teacher" in value ? UserRole.teacher : "student" in value ? UserRole.student : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    graded: null;
} | {
    submitted: null;
} | {
    grading: null;
}): SubmissionStatus {
    return "graded" in value ? SubmissionStatus.graded : "submitted" in value ? SubmissionStatus.submitted : "grading" in value ? SubmissionStatus.grading : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exam>): Promise<Array<Exam>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Exam_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Promise<Array<Submission>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Submission_n40(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PerformanceRecord>): Array<PerformanceRecord> {
    return value.map((x)=>from_candid_PerformanceRecord_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_UserId, _UserProfile]>): Array<[UserId, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n53(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_QuestionType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n57(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pointValue: bigint;
    text: string;
    correctAnswer?: string;
    questionType: QuestionType;
    questionId: QuestionId;
    options: Array<string>;
}): {
    pointValue: bigint;
    text: string;
    correctAnswer: [] | [string];
    questionType: _QuestionType;
    questionId: _QuestionId;
    options: Array<string>;
} {
    return {
        pointValue: value.pointValue,
        text: value.text,
        correctAnswer: value.correctAnswer ? candid_some(value.correctAnswer) : candid_none(),
        questionType: to_candid_QuestionType_n13(_uploadFile, _downloadFile, value.questionType),
        questionId: value.questionId,
        options: value.options
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    shortAnswer: null;
} | {
    essay: null;
} | {
    multipleChoice: null;
} {
    return value == QuestionType.shortAnswer ? {
        shortAnswer: null
    } : value == QuestionType.essay ? {
        essay: null
    } : value == QuestionType.multipleChoice ? {
        multipleChoice: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.teacher ? {
        teacher: null
    } : value == UserRole.student ? {
        student: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Question>): Array<_Question> {
    return value.map((x)=>to_candid_Question_n11(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
